apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kustomization-test
  name: myapp-deployment
spec:
  replicas: 3 # increase the number of replicas.
  template:
    spec:
      containers:
      - name: nginx
        resources: # adjust resource requests and limits for testing.
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"